- fail:
    msg: "Only Ubuntu and Debian are supported"
  when: ansible_distribution not in ["Ubuntu","Debian"]
  tags:
  - always

- name: "Install dependencies"
  become: yes
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    update_cache: yes

- name: "Install GPG key"
  become: yes
  apt_key:
    # https://download.docker.com/linux/ubuntu/gpg
    url: "https://download.docker.com/linux/{{ansible_distribution|lower}}/gpg"
    state: present

- name: "Install apt repository"
  become: yes
  apt_repository:
    # deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
    repo: "deb https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable"
    state: present
    filename: docker

- name: "Install docker"
  become: yes
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    update_cache: yes
