- fail:
    msg: "Only Ubuntu and Debian are supported"
  when: ansible_distribution not in ["Ubuntu","Debian"]
  tags:
  - always

- name: Call setup_hostname
  include_tasks:
    file: "setup_hostname.yml"

- name: Call upgrade_packages
  include_tasks:
    file: "upgrade_packages.yml"

- name: Call grow_lvm
  include_tasks:
    file: "grow_lvm.yml"
  when: lvmap is defined


- name: Reboot the machine
  become: yes
  reboot:
